[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; [FIX] Use the standard partition table name
board_build.partitions = default.csv

lib_deps = 
	FS
	SPIFFS
	bblanchon/ArduinoJson@^7.4.2
	andrealombardo/L298N@^2.0.3